-- StackItUp — supplement library seed data (29 rows)
-- Snapshot exported from the live database on 2026-08-12.
--
-- Idempotent: each row upserts by `key` (on conflict do update), so this file is
-- safe to run repeatedly. On a fresh database it populates the library; on an
-- existing one it brings every row in line with this snapshot.
--
-- Prereq: the `supplements` table and its metadata columns must exist first —
-- run docs/supabase-auth-setup.sql (through section 9) before this file.
--
-- To refresh after editing supplements in the admin panel, RE-EXPORT from the
-- database rather than hand-editing rows here, so this stays a faithful mirror.

begin;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('caffeine_ltheanine', 'Caffeine + L-Theanine', '☕', 'Caffeine for alertness, L-theanine to take the edge off the jitters. Caffeine''s performance effect is very well established; the combination has smaller but consistent focus data.', 'Morning or pre-workout. Avoid after 2pm.', '100–200mg caffeine / 200mg L-theanine', '{energy,brain,fat_loss}'::text[], 'cognitive', 'strong', 'This adds to the caffeine already in your coffee, tea and pre-workout. Can worsen anxiety, raise blood pressure and disrupt sleep for up to 8 hours. Interacts with some antidepressants and heart medication.', 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('l_tyrosine', 'L-Tyrosine', '🧠', 'A dopamine precursor that helps hold cognitive performance together under acute stress, cold, or sleep loss. Little to no effect when you are already well rested.', '30–60 minutes before a demanding or sleep-deprived stretch.', '500–2000mg', '{brain,stress,energy}'::text[], 'cognitive', 'moderate', NULL, 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('lions_mane', 'Lion''s Mane Mushroom', '🍄', 'Best known for stimulating nerve growth factor (NGF) in laboratory studies. Human cognitive trials are early and small — promising rather than proven.', 'Morning or early afternoon.', '500–1000mg extract', '{brain,energy,health}'::text[], 'cognitive', 'emerging', NULL, 30, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('vitd3', 'Vitamin D3 + K2', '☀️', 'Deficiency is common, especially at northern latitudes and in winter. Supports immune function, bone density and mood. K2 is included to direct calcium to bone rather than arteries.', 'Morning with a fatty meal.', '2,000–5,000 IU D3 / 100mcg K2', '{health,immune,muscle}'::text[], 'foundational', 'strong', 'The K2 in this combination interferes with warfarin and other anticoagulants. If you take a blood thinner, do not start this without talking to whoever manages your prescription.', 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('omega3', 'Omega-3 Fish Oil', '🐟', 'EPA and DHA lower triglycerides and support heart, brain and joint health. One of the few supplements with large, consistent human trial data behind it.', 'With meals to reduce fishy aftertaste.', '2–3g EPA+DHA daily', '{health,joints,brain,fat_loss}'::text[], 'foundational', 'strong', 'Doses above roughly 3g a day may increase bleeding risk, particularly alongside anticoagulants or regular NSAID use. Stop two weeks before planned surgery.', 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('b12', 'Vitamin B12', '💊', 'Essential for energy production and nerve health. Critical for vegans and vegetarians who can''t get it from food.', 'Morning with breakfast.', '500–1000mcg methylcobalamin', '{vegan,vegetarian,energy,health}'::text[], 'foundational', 'strong', NULL, 30, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('iron', 'Iron (Bisglycinate)', '🔩', 'Plant-based diets are lower in bioavailable iron, leading to fatigue. Bisglycinate is gentle on the stomach.', 'On an empty stomach or with vitamin C.', '18–25mg', '{vegan,vegetarian,energy}'::text[], 'foundational', 'strong', 'Only supplement iron if a blood test has shown you are low — excess iron accumulates and is harmful. Iron overdose is a leading cause of poisoning in young children, so keep it well out of reach. Separate it by at least two hours from thyroid medication, antibiotics and calcium.', 40, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('multivitamin', 'Multivitamin', '🌈', 'Insurance against small gaps rather than a performance tool. Most useful if your diet is restricted, monotonous, or you are eating in a deficit. It will not out-run a poor diet.', 'With your largest meal.', 'One serving', '{health,immune,vegan,vegetarian}'::text[], 'foundational', 'moderate', NULL, 50, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('vitamin_c', 'Vitamin C', '🍊', 'Supports immune function and sharply improves iron absorption from plant foods. It does not prevent colds in the general population, but it does shorten them slightly and helps people under heavy physical stress.', 'With food. Split the dose if taking more than 500mg.', '250–1000mg', '{immune,health,vegan,vegetarian}'::text[], 'foundational', 'moderate', NULL, 60, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('coq10', 'CoQ10 (Ubiquinol)', '🔋', 'Part of how your cells produce energy. The clearest benefit is for people taking statins, which deplete it, and for adults over 40 whose natural levels have dropped. General energy claims are weaker.', 'With a fat-containing meal.', '100–200mg ubiquinol', '{energy,health,recovery}'::text[], 'foundational', 'moderate', NULL, 70, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('nac', 'NAC (N-Acetyl Cysteine)', '🧪', 'Precursor to glutathione, your body''s main antioxidant. Well established clinically for mucus clearance and liver support; the mood and compulsive-behaviour research is more mixed.', 'On an empty stomach, away from food.', '600–1200mg', '{health,immune,recovery}'::text[], 'foundational', 'moderate', 'May trigger bronchospasm in some people with asthma. Can extend bleeding time, so take care if you are on anticoagulants or approaching surgery.', 80, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('probiotic', 'Probiotic (Multi-Strain)', '🦠', 'Effects are strain-specific rather than general. Best evidence is for antibiotic-associated digestive upset and IBS symptoms; look for a product that names its strains.', 'Morning on an empty stomach.', '10–50 billion CFU', '{gut,immune,health}'::text[], 'gut_digestion', 'moderate', NULL, 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('fibre', 'Psyllium Fibre', '🌾', 'Improves stool consistency in both directions, lowers LDL cholesterol, and blunts blood sugar spikes. Increase the dose gradually and drink plenty of water with it.', 'With a large glass of water, away from other supplements.', '5–10g', '{gut,health,fat_loss,keto}'::text[], 'gut_digestion', 'strong', NULL, 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('berberine', 'Berberine', '🍃', 'Lowers fasting blood glucose and improves blood lipids in trials. Note that it interacts with a long list of prescription medications — check with a pharmacist or doctor before starting.', 'Just before meals.', '500mg, two to three times daily', '{gut,health,fat_loss}'::text[], 'gut_digestion', 'moderate', 'Interacts with a long list of prescription medicines, including metformin, statins, ciclosporin and blood thinners. Not for use in pregnancy or breastfeeding. Check with a pharmacist before starting.', 30, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('collagen', 'Collagen Peptides', '🦷', 'Reasonable evidence for skin elasticity and activity-related joint discomfort. The gut-lining claim is popular but not well supported.', 'Pre-workout or with morning coffee.', '10–15g', '{joints,gut,health,recovery}'::text[], 'joints_skin', 'moderate', NULL, 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('curcumin', 'Curcumin (with Piperine)', '🫚', 'Anti-inflammatory with decent trial data for osteoarthritis knee pain. Plain turmeric powder is poorly absorbed, so the delivery form matters more than the headline dose.', 'With meals.', '500–1000mg curcuminoids, with piperine or in a bioavailable form', '{joints,health,recovery}'::text[], 'joints_skin', 'moderate', NULL, 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('creatine', 'Creatine Monohydrate', '⚡', 'The most well-researched supplement for muscle strength and power output. Proven to increase lean mass and performance.', 'Any time of day — consistency matters more than timing.', '3–5g daily', '{muscle,recovery,intense,vegan,vegetarian}'::text[], 'performance', 'strong', NULL, 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('protein', 'Whey Protein', '🥛', 'Ensures you hit daily protein targets to support muscle repair and growth, especially after training.', 'Post-workout or between meals.', '25–40g per serving', '{muscle,recovery,fat_loss,intense}'::text[], 'performance', 'strong', NULL, 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('beta_alanine', 'Beta-Alanine', '🔥', 'Buffers acid build-up during hard efforts lasting roughly one to four minutes — high-rep sets, rowing, sprint intervals. The harmless skin tingling is normal and fades with use.', 'Any time of day. Daily intake matters, not timing.', '3–6g daily, split to reduce tingling', '{muscle,intense,recovery}'::text[], 'performance', 'strong', NULL, 30, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('citrulline', 'L-Citrulline', '🍉', 'Raises nitric oxide and blood flow, modestly increasing training volume and reducing next-day soreness. The effect is real but smaller than pre-workout marketing implies.', '30–60 minutes pre-workout.', '6–8g L-citrulline (or 8–10g citrulline malate)', '{muscle,intense,recovery}'::text[], 'performance', 'moderate', NULL, 40, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('beetroot', 'Beetroot / Nitrate', '🧃', 'Dietary nitrate improves oxygen efficiency and endurance, with the clearest benefit for recreational rather than elite athletes. Antibacterial mouthwash blocks the conversion, so skip it beforehand.', '2–3 hours before endurance work.', '~400–800mg nitrate (500ml juice or one concentrated shot)', '{energy,intense,health}'::text[], 'performance', 'strong', 'Dietary nitrate lowers blood pressure, which can stack with blood pressure medication. Harmless red urine and stools are common and not a cause for concern.', 50, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('electrolytes', 'Electrolytes', '💧', 'Replenishes sodium, potassium, and magnesium lost through sweat. Prevents cramps and sustains performance.', 'During or after intense workouts.', '1 packet or serving', '{intense,moderate,recovery,keto}'::text[], 'performance', 'strong', NULL, 60, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('taurine', 'Taurine', '💦', 'Involved in muscle contraction and fluid balance. Small but consistent effects on endurance and post-exercise soreness. Often paired with caffeine to smooth its edge.', 'Pre-workout, or with your evening meal.', '1–3g daily', '{muscle,recovery,energy}'::text[], 'performance', 'moderate', NULL, 70, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('magnesium', 'Magnesium Glycinate', '🌙', 'Roughly half of adults fall short of the RDA. May improve sleep quality and reduce muscle cramps; glycinate is the gentlest form on the stomach.', '30–60 minutes before bed.', '300–400mg', '{sleep,stress,joints,recovery,keto}'::text[], 'sleep_stress', 'moderate', NULL, 10, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('glycine', 'Glycine', '🛌', 'Slightly lowers core body temperature, which helps you fall asleep faster. Small trials report better sleep quality and less next-day fatigue. Cheap, and mildly sweet to taste.', '30–60 minutes before bed.', '3g', '{sleep,recovery,stress}'::text[], 'sleep_stress', 'moderate', NULL, 20, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('ashwagandha', 'Ashwagandha KSM-66', '🌿', 'Adaptogen with reasonable trial support for reducing perceived stress and cortisol. Testosterone effects exist in the literature but are small and inconsistent.', 'Morning or evening — take consistently.', '300–600mg', '{stress,sleep,health,recovery}'::text[], 'sleep_stress', 'moderate', 'Can affect thyroid hormone levels and interacts with sedatives, thyroid medication and immunosuppressants. There are rare reports of liver injury. Avoid in pregnancy, and stop before surgery.', 30, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('rhodiola', 'Rhodiola Rosea', '🏔️', 'Adaptogen studied for fatigue and burnout, with encouraging results in stressed and sleep-deprived people. Trial quality is mixed, so treat it as promising rather than settled.', 'Morning on an empty stomach — can disrupt sleep if taken late.', '200–400mg (3% rosavins / 1% salidroside)', '{stress,energy,brain}'::text[], 'sleep_stress', 'emerging', NULL, 40, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('zinc_mag', 'ZMA (Zinc + Magnesium + B6)', '🏆', 'Zinc and magnesium both matter if you are running low. The testosterone-boosting claim behind ZMA has not held up in men who already have adequate zinc — treat it as a sleep and immune support stack.', '30–60 minutes before bed on an empty stomach.', 'As directed (typically 30mg zinc / 450mg Mg)', '{muscle,sleep,intense,immune}'::text[], 'sleep_stress', 'emerging', NULL, 50, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

insert into public.supplements (key, name, emoji, why, timing, dose, tags, category, evidence, warnings, sort_order, is_active) values ('inositol', 'Myo-Inositol', '⚖️', 'Strongest evidence is for insulin sensitivity and cycle regularity in PCOS. Also studied for anxiety, though at considerably higher doses. Very well tolerated.', 'Split morning and evening, or take it all before bed.', '2–4g daily', '{stress,health,sleep}'::text[], 'sleep_stress', 'moderate', 'Generally very well tolerated. It does affect blood sugar, so coordinate with your doctor if you take diabetes medication. Higher doses can cause mild digestive upset.', 60, true)
  on conflict (key) do update set name=excluded.name, emoji=excluded.emoji, why=excluded.why, timing=excluded.timing, dose=excluded.dose, tags=excluded.tags, category=excluded.category, evidence=excluded.evidence, warnings=excluded.warnings, sort_order=excluded.sort_order, is_active=excluded.is_active;

commit;
